// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Map from "rescript/lib/es6/belt_Map.js";
import * as IconData$RescriptReactWebpackTailwindTemplate from "./IconData.bs.js";

function string(prim) {
  return prim;
}

function IconDisplay(Props) {
  return React.createElement("div", {
              className: "flex flex-col gap-2"
            }, React.createElement("div", {
                  className: "x-rounded"
                }, "search panel"), React.createElement("div", {
                  className: "flex flex-col md:flex-row h-full justify-between gap-1"
                }, React.createElement("div", {
                      className: "flex-1 flex flex-col gap-1"
                    }, React.createElement("span", {
                          className: "block text-base"
                        }, "Outline"), React.createElement("div", {
                          className: "x-rounded items-center justify-center flex-1 h-screen p-2 gap-2"
                        }, IconData$RescriptReactWebpackTailwindTemplate.paperAirPlane, Belt_Map.getWithDefault(IconData$RescriptReactWebpackTailwindTemplate.solidIcons, "PaperAirPlane", React.createElement("div", undefined)))), React.createElement("div", {
                      className: "flex-1 flex flex-col"
                    }, React.createElement("span", {
                          className: "block text-base "
                        }, "Solid"), React.createElement("div", {
                          className: "x-rounded flex-1 h-screen"
                        }))));
}

var make = IconDisplay;

export {
  string ,
  make ,
  
}
/* react Not a pure module */
