// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Util$RescriptHeroiconsBindingDemo from "../../util.bs.js";

function IconBox(Props) {
  var name = Props.name;
  var type_ = Props.type_;
  var children = Props.children;
  var handleOnClick = function (e) {
    e.preventDefault();
    return Util$RescriptHeroiconsBindingDemo.copy("<Heroicons." + type_ + "." + name + "Icon className=\"h-6 w-6\" />");
  };
  return React.createElement("div", {
              className: "flex flex-col items-center justify-center w-24 antialiased"
            }, React.createElement("div", {
                  className: "group border border-primary_200 p-2 h-16 w-24\n                 rounded flex flex-col justify-center items-center relative hover:border-2"
                }, React.createElement(React.Fragment, undefined, children, React.createElement("div", {
                          className: "justify-center place-items-center font-sans tracking-tight font-light text-[0.7em] \n                     bg-primary_200 absolute w-11/12 h-1/2 bottom-1 rounded cursor-pointer hidden \n                     group-hover:flex active:bg-primary_300",
                          style: {
                            opacity: "0.7"
                          },
                          onClick: handleOnClick
                        }, React.createElement("span", undefined, "Copy JSX")))), React.createElement("span", {
                  className: "font-sans tracking-tight text-primary_600 block pt-2 text-[0.7em]"
                }, name));
}

var make = IconBox;

export {
  make ,
  
}
/* react Not a pure module */
