// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function IconBox(Props) {
  var name = Props.name;
  var children = Props.children;
  return React.createElement("div", {
              className: "flex flex-col items-center justify-center"
            }, React.createElement("div", {
                  className: "border border-primary_200 p-2 h-16 w-24 min-w-24\n            rounded hover:border-2 hover:drop-shadow-lg \n            flex justify-center items-center"
                }, children), React.createElement("span", {
                  className: "font-mono font-thin tracking-tighter text-primary_600 block pt-2 text-[0.7em]"
                }, name));
}

var make = IconBox;

export {
  make ,
  
}
/* react Not a pure module */
