// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Outline from "@heroicons/react/outline";

function NotFound(Props) {
  return React.createElement("div", {
              className: "flex flex-col h-full justify-center items-center gap-[2px] pt-[56px] md:pt-[48px] z-0"
            }, React.createElement(Outline.EmojiSadIcon, {
                  className: "h-20 w-20  text-primary_300"
                }), React.createElement("span", {
                  className: "block text-primary_300"
                }, "Sorry! No icons found."));
}

var make = NotFound;

export {
  make ,
  
}
/* react Not a pure module */
