// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";
import * as About$RescriptHeroiconsBindingDemo from "./About.bs.js";
import * as NavBar$RescriptHeroiconsBindingDemo from "./NavBar.bs.js";
import * as IconDisplay$RescriptHeroiconsBindingDemo from "./IconDisplay/IconDisplay.bs.js";

function string(prim) {
  return prim;
}

function useState(prim) {
  return React.useState(function () {
              return Curry._1(prim, undefined);
            });
}

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var component;
  var exit = 0;
  if (match && match.hd === "about" && !match.tl) {
    component = React.createElement(About$RescriptHeroiconsBindingDemo.make, {});
  } else {
    exit = 1;
  }
  if (exit === 1) {
    component = React.createElement(IconDisplay$RescriptHeroiconsBindingDemo.make, {});
  }
  var match$1 = React.useState(function () {
        return "theme-gray";
      });
  return React.createElement("div", {
              className: "" + match$1[0] + " flex flex-col"
            }, React.createElement(NavBar$RescriptHeroiconsBindingDemo.make, {
                  setTheme: match$1[1]
                }), React.createElement("div", {
                  className: "py-[56px] bg-primary_50 h-screen px-6"
                }, component));
}

var make = App;

export {
  string ,
  useState ,
  make ,
  
}
/* react Not a pure module */
