// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";
import * as HeroLogo$RescriptReactWebpackTailwindTemplate from "./HeroLogo.bs.js";
import * as ThemeMenu$RescriptReactWebpackTailwindTemplate from "./ThemeMenu.bs.js";

function string(prim) {
  return prim;
}

function NavBar(Props) {
  var setTheme = Props.setTheme;
  return React.createElement("nav", {
              className: "bg-primary_100 py-1 fixed inset-x-0 shadow flex-1"
            }, React.createElement("div", {
                  className: "px-2"
                }, React.createElement("div", {
                      className: "flex justify-between items-center"
                    }, React.createElement("div", {
                          className: "flex space-x-2"
                        }, React.createElement("div", {
                              className: "pt-1 h-12 w-12"
                            }, React.createElement("a", {
                                  href: "https://heroicons.com/",
                                  target: "blank"
                                }, React.createElement(HeroLogo$RescriptReactWebpackTailwindTemplate.make, {}))), React.createElement("div", {
                              className: "flex items-center text-primary_600"
                            }, React.createElement("button", {
                                  className: "navbar-button",
                                  type: "button",
                                  onClick: (function (param) {
                                      return RescriptReactRouter.push("/");
                                    })
                                }, React.createElement("a", {
                                      className: "navbar-menu-text"
                                    }, "Home")), React.createElement("button", {
                                  className: "navbar-button",
                                  type: "button",
                                  onClick: (function (param) {
                                      return RescriptReactRouter.push("about");
                                    })
                                }, React.createElement("a", {
                                      className: "navbar-menu-text"
                                    }, "About")))), React.createElement("div", {
                          className: "flex items-center space-x-2 pr-4 relative"
                        }, React.createElement(ThemeMenu$RescriptReactWebpackTailwindTemplate.make, {
                              setTheme: setTheme
                            })))));
}

var make = NavBar;

export {
  string ,
  make ,
  
}
/* react Not a pure module */
